# .github/workflows/security-scan.yml
name: Security Scanning Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ "${{ github.event_name }}" = "push" ]; then
            pip install -r requirements/base.txt
          else
            pip install -r requirements/test.txt
          fi

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Security Scan
        env:
          COSMOS_DB_CONNECTION_STRING: ${{ secrets.COSMOS_DB_CONNECTION_STRING }}
          COSMOS_DB_DATABASE_NAME: ${{ secrets.COSMOS_DB_DATABASE_NAME }}
          COSMOS_DB_CONTAINER_NAME: ${{ secrets.COSMOS_DB_CONTAINER_NAME }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          python -c "
          import asyncio
          import json
          import logging
          from src.scanners.scanning_service import ScanningService
          
          # Configure logging
          logging.basicConfig(
              level=logging.INFO,
              format='%(asctime)s - %(levelname)s - %(message)s'
          )
          
          async def run_scan():
              scanner = ScanningService()
              results = await scanner.run_scan()
              print('Scan Results:', json.dumps(results, indent=2))
              
              # Save results to file
              with open('scan_results.json', 'w') as f:
                  json.dump(results, f, indent=2)
                  
              return results
          
          results = asyncio.run(run_scan())
          
          # Check for scan failure
          if results.get('status') == 'failed':
              print('Scan failed:', results.get('error'))
              exit(1)
          "

      - name: Upload Scan Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            scan_results.json
            *.log